### ISSUE TITLE
Add Hampton City Crime Data

### ISSUE THREAD

**Issue by qwo** [Code4HR/hercules#1]
Hampton is archived on the pilot online page but @jonahadkins began an effort to start putting together hampton crime data maps after the city police department started an open data page. 

The project can be found https://github.com/Code4HR/hampton-police-open-data with the dataset in the repo and readme notes where he gets the data from. He mentioned the data goes back to 2009.

He has the data uploaded to CartoDB and he put a map on it viewable at http://code4hr.github.io/hampton-police-open-data

**Comment by blackhatbrigade** [comment]
The pilot data was self-confessed to be a little off (I think we had some data come back for somewhere in Utah?).   We're definitely interested in the linked project.  I'll dig into it as I get time.

Definitely a good link.

**Comment by asedarski** [comment]
I also really like the way that the crimes are defined in different colors for the severity. Another possible way for us to distinguish between major and minor crimes.

**Comment by XxNoFriendsxX** [comment]
Red = Murder / Attempted Murder
Orange = Rape / Assault / Child Molestation
Yellow = Robbery / Car Jacking / Drug Distribution / Domestic Disturbance
Green = Fraud / Drug Possession
Brown = DUI / Drunk In Public / Public Intoxication

Tapping into my First 48 / Law & Order / Minority Report cop show knowledge.

**Comment by XxNoFriendsxX** [comment]
crimemapping.com uses specific icons which is also neat

**Comment by asedarski** [comment]
http://www.hampton.gov/index.aspx?nid=2930

Table format of quarterly crime info with block number and identifier

**Comment by asedarski** [comment]
http://www.hampton.gov/index.aspx?nid=2930

Table format of quarterly crime info with block number and identifier. The table is able to be downloaded. Might be a much easier place for us to start with crime.
AND there is an API we can hit
https://dev.socrata.com/foundry/data.hampton.gov/umc3-tsey

**Comment by asedarski** [comment]
Another option but for Newport News. We would have to slowly build up our database, but they have daily crime reports here http://www.nngov.com/744/Daily-Offense-Reports by day of the week.

**Comment by hop-along-polly** [comment]
I had crime data in ES, but due to the poor implementation of ES and it's miserable documentation I ended up removing the index with all that data. Working on getting that fixed again and then i'll insert the data again.

**Comment by josibake** [comment]
ES implementation fixed. Updated refresh-timestamp index and hercules-crime_v1 index.

**Comment by josibake** [comment]
created hercules-refresh_timestamp_v1 index

**Comment by hop-along-polly** [comment]
Data is in ES. Removed code for HRQLS code base that could duplicate data if run multiple times.
