### ISSUE TITLE
Dockerize Hercules and support Local Dev on Docker + Autodeploy to Cloud

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/hercules#10]
- [x] create Dockerfiles for each repo
- [x] create Docker Compose file to connect containers
- [x] configure Travis CI to deploy to DO on master commit
- [x] create documentation on how dev's can run all repos locally for easy dev via docker-toolkit

**Comment by BretFisher** [comment]
Based off new dockerize branch, I need to check where this was before holidays and get into digital ocean single-server.

**Comment by BretFisher** [comment]
This all works in hercules for myself, and @asedarski so I'd like a few others to test the dockerize branch and see if we can't get signoff to merge it to master. The goals are to support:
1. people developing how they used to, without docker. These would be people with an established workflow of php5, composer, apache, etc.
2. support docker-based development locally. Only requires dev to have docker working, and not no anything about which php5 version, apache, or any other dependencies to get started on project.

**Comment by asedarski** [comment]
I'm able to get Hercules running locally on Docker. Are we at a point now that we can merge the Dockerize branch into Master?
