### ISSUE TITLE
Bug in Bootstrap.php?

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/hercules#13]
I try to startup hercules API and get this: 
`Parse error: syntax error, unexpected '.', expecting ']' in /var/www/html/src/HRQLS/Bootstrap.php on line 75`

**Comment by hop-along-polly** [comment]
Bret,

You can remove the array of Crimes URL's and the loop dealing with the
crime scraper from the bootstraps constructor. My PR will be moving those.
I couldn't see exactly what was wrong but if they are causing issues just
get rid of them for now.

**Comment by hop-along-polly** [comment]
This was resolved with [PR#18](https://github.com/Code4HR/hercules/pull/18)
