### ISSUE TITLE
Add School Data API

### ISSUE THREAD

**Issue by hop-along-polly** [Code4HR/hercules#24]
1.) Register to use Great Schools API
2.) create /Schools facade endpoint.

**Comment by hop-along-polly** [comment]
We are waiting to hear back from Bret on whether we can/should use Code for HR info when registering for this API.

**Comment by BretFisher** [comment]
Did I miss a conversation? Sure you can use your own info or ours.  No idea what you're really asking for though.

**Comment by asedarski** [comment]
I have submitted a request to GreatSchools.org for a key to their API. I am waiting to hear back. I submitted it under the new hercules.code4hr@gmail.com email address

**Comment by asedarski** [comment]
API Key:
whagxohxlmx5y3spayud7axx 

The A API has a 3,000 call limit per day. We'll be charged for going over that.

**Comment by qwo** [comment]
i wouldn't recommend posting your API key online! or you'll definitely end up going over :)

Recommend regenerating!

**Comment by hop-along-polly** [comment]
PR#53 is in that provides data for Hampton, Norfolk, VA Beach, Portsmouth, Chesapeake, and Suffolk.

**Comment by hop-along-polly** [comment]
I'll add one shortly that connects all of these cities as one dataset.
