### ISSUE TITLE
Research Census Data API

### ISSUE THREAD

**Issue by hop-along-polly** [Code4HR/hercules#25]
During one of the hack days we found the Census API may not be suitable for our purposes. We wanted to retrieve data based on a general search criteria such as city name, zip code etc. The dev working on this said the API would not return any information without specifying a street name. This is to specific for us as we would have to query the API for each street before being able to display data for an entire region. We need to determine is there is some other way to return data from the census API or find another data source for economic and cost of living data.

**Comment by josibake** [comment]
Census API will allow data to be returned at state, county, city, block group level.  A block group is a geographic region containing 600 ~ 3,000 people.  Looks like the census api will decode zipcodes, address, lat long, etc to their appropriate block group.  Working on some example calls.

API key:  88712ee71e48b33d4fc366e2e66c51a05e61fbda

**Comment by josibake** [comment]
http://api.census.gov/data/2014/acs5?get=B19013_001E&for=block+group:*&in=state:51+county:650

api call for pulling median income by block in hampton city

**Comment by josibake** [comment]
no api key needed?  not sure when it is required vs not required

**Comment by josibake** [comment]
http://www.bls.gov/data/
https://fred.stlouisfed.org/

**Comment by asedarski** [comment]
http://data.openva.com/dataset?tags=Income+Taxes

**Comment by josibake** [comment]
api key for bls.gov/data

465969c922f4402fbe76f536a4b8d71a
