### ISSUE TITLE
setup elasticsearch service provider

### ISSUE THREAD

**Issue by josibake** [Code4HR/hercules#33]

**Comment by josibake** [comment]
for what we are using elasticsearch for, we do not need strings to be analyzed.  Setting a template for turning string_analyzer off:

curl -XPUT 'hercules.code4hr.org:33366/_template/hercules_template' -d '{
    "template": "hercules_",
    "settings": {
        "number_of_shards": 3
    },
    "mappings": {
        "crime": {
            "dynamic_templates": [{
                    "strings_not_analyzed": {
                        "match": "_",
                        "match_mapping_type": "string",
                        "mapping": {
                            "type": "string",
                            "index": "not_analyzed"
                        }
                    }
                }
                ]
            }
    }
}'

**Comment by hop-along-polly** [comment]
Reading up on the ES documentation the above template will not be very useful at all.

**Comment by josibake** [comment]
bms?

**Comment by hop-along-polly** [comment]
@josibake I don't know what bms means...let's try English.

**Comment by josibake** [comment]
Be more specific?

**Comment by hop-along-polly** [comment]
I'm thinking there should be an index for each city and then the type would be the data. i.e.
 Index = Hampton, 
    types=[crime, schools, census]
Index=Norfolk
    types=[crime, census]

It'll make more sense when I finish the template/mapping/schema whatever the heck ES calls it. The data will be better organized and queries will be easier to write for cross city comparison/filtering.

**Comment by josibake** [comment]
set up template for all hercules indexes using:

{
    "template": "hercules-*",
    "settings": {
        "number_of_shards": 3
    },
    "mappings": {
        "_default_": {
            "_all": {
                "enabled": false
            },
            "dynamic_templates": [{
                "strings": {
                    "match_mapping_type": "string",
                    "unmatch": "location",
                    "mapping": {
                        "type": "string",
                        "index": "not_analyzed"
                    }
                }
            },
            {
                "locations": {
                    "match": "location",
                    "mapping": {
                        "type": "geo_point"
                    }
                }
            },
            {
                "dates":{
                    "match":"date_time",
                    "mapping":{
                        "type":"date"
                    }
                }
            }]
        }
    }
}

tested by loading:

curl -XPOST 'hercules.code4hr.org:33366/hercules-crime/crimes/' -d'
{"location": "37.0445242,-76.3916231","city":"Hampton","category":"Theft","date_time":"2016-04-01T00:00:00.000","offense":"FRAUD, CREDIT CARD","class":"This was a very bad crime"}'

and everything looks good.  

In the template, any time "location" is used in any index, it will be mapped to a geo_point, so if we add a schools index, it should have a location field.  Same for date_time.  Any time date_time is used it will be mapped to a date in any index.

Per our discussion yesterday @ezzy1337 , and some more reading, went ahead and created a hercules-dataset index, and just used "crimes" as the type.  The index is created and the mappings are set, so you can start pushing and pulling data.  I'll comment an example of indexing with a bulk request as well.
