### ISSUE TITLE
Pick our first City

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/hercules#4]
We need to pick which city we'll focus on first. I was thinking "the easiest for us to get ~5 useful datasets from". Based on the idea that we're potentially combining demographic data (US Census), city department data (crime, biz licenses, etc.), and maybe social data (public art, events, bike paths, etc.), which city could we get off the ground the fastest?

It would likely help if we had some User Stories first that described specific data sets needed to solve a single problem, then backfilled which HR cities already have that data public, and the quality of that data.

We should use the official US Data Census to find where the popular datasets are, and optionally fill out the Census more if it's out dated: http://us-city.census.okfn.org/place/norfolk

**Comment by asedarski** [comment]
We've decided on Virginia Beach as a first city to implement for Hercules and Explore
