### ISSUE TITLE
Explore alternative data sets/supplemental data sets

### ISSUE THREAD

**Issue by josibake** [Code4HR/hercules#5]
Look for interesting/meaningful data to supplement crime/education/cost of living

**Comment by hop-along-polly** [comment]
The datasets chosen were Hampton City Crime, Great Schools for Hampton, VA Beach, Norfolk, Portsmouth, Chesapeake and Suffolk, and Census data for the same cities. No further exploration into datasets needs to occur. If a developer wants to add a data set then they can put in a PR.
