### ISSUE TITLE
Finish Code cleanup and release Feature freeze

### ISSUE THREAD

**Issue by blackhatbrigade** [Code4HR/hercules#8]
We're currently in a feature freeze for the HRQLS codebase until we can finish some house cleaning.  The current items on the board to complete the cleanup are:
- [x] Implement code standard and bring existing code up to standard
  - [x] Enforce phpdoc so code documentation can be automated
- [x] Update build process for ease of quality control
  - [x] Automate documentation generation
  - [x] Automate test coverage reports
- [x] Reach 70% test coverage of code base

Ultimately we'll aim for a higher test coverage, but we're trying to keep intital cleanup reasonable and reachable in a short amount of time.  We're holding a feature freeze until we can reach this milestone so we're not aiming for a moving target.  This should be completed within 2 weeks of this issue being completed (if not sooner).

**Comment by blackhatbrigade** [comment]
Completed the report generation.  It actually was already done, just had a mistyped directory.

Extended the test coverage and even abstracted the database connection.

**Comment by BretFisher** [comment]
Finishing this up in `build` branch. Once this API is working it'll be merged into master branch and pushed to Digital Ocean server.
